### ISSUE TITLE
Unhandled Exception: RangeError (byteOffset): Index out of range: index should be less than 146292208: 1179937898

### ISSUE THREAD

**Issue by romancores** [bdero/flutter_scene#53]
Reproducing the test scene with own .glb model is returning error for bytes offset.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: RangeError (byteOffset): Index out of range: index should be less than 146292208: 1179937898
#0      _byteDataByteOffsetCheck (dart:typed_data-patch/typed_data_patch.dart:5465:5)
#1      _ByteDataView.getInt32 (dart:typed_data-patch/typed_data_patch.dart:5207:5)
#2      BufferContext._getInt32 (package:flutter_scene_importer/third_party/flat_buffers.dart:70:40)
#3      Reader._vTableFieldOffset (package:flutter_scene_importer/third_party/flat_buffers.dart:1054:34)
#4      Reader.vTableGetNullable (package:flutter_scene_importer/third_party/flat_buffers.dart:1048:25)
#5      Scene.nodes (package:flutter_scene_importer/generated/scene_impeller.fb_flatbuffers.dart:3118:67)
#6      Node.fromFlatbuffer (package:flutter_scene/src/node.dart:142:51)
#7      Node.fromAsset (package:flutter_scene/src/node.dart:131:12)
```

Steps to reproduce:
- create new flutter project with gpu support (master channel latest)
- add .glb model to models/some_model.glb
- run flutter_scene_importer for this model
- run app and receive error on  Node.fromAsset('models/some_model.glb')

**Comment by Mohammad-R-Rashid** [comment]
Hello @romancores . How did you solve this issue? I'm on iOS
